## Test stuff [/test]
### Test Get [GET]
+ Response 200 (application/json)

        {
            "test": "testing"
        }

### Test Post [POST]
+ Response 201 (application/json)

        {
            "created": true
        }